# -*- coding: utf-8 -*-
"""spotify_data_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wn8haCYl9g3Dwmlgoc78IURXoXdOj5f_

**Import Required Libraries**
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""**Exploring the Dataset**

### Uploading CSV Files from Local Machine
Run the cell below to open a file selection dialog. Please choose your CSV files (e.g., `tracks.csv` and `artists.csv`).
"""

from google.colab import files

print("Please select your CSV files to upload:")
uploaded = files.upload()

for filename in uploaded.keys():
  print(f'User uploaded file "{filename}" with length {len(uploaded[filename])} bytes')

sp_tracks = pd.read_csv('tracks.csv')
sp_artists = pd.read_csv('artists.csv')

print("First 5 rows of sp_tracks:")
display(sp_tracks.head())

print("\nFirst 5 rows of sp_artists:")
display(sp_artists.head())

"""**Identifying Null Values in the Dataset**"""

pd.isnull(sp_tracks).sum()

pd.isnull(sp_artists).sum()

"""**Dataset Overview: Rows, Columns, Data Types, and Memory Usage**"""

sp_tracks.info()

sp_artists.info()

"""**Extracting Insights from the Dataset through Analysis📊**

**1. Exploring the 10 Least Popular Songs in the Spotify Dataset**
"""

a=sp_tracks.sort_values('popularity',ascending=True)[0:10]
a[['name','popularity']]

"""**2. Descriptive Statistics**"""

# descriptive statistics of tracks
sp_tracks.describe().transpose()

"""**3. Discovering the Top 10 Popular Songs in the Spotify Dataset**"""

a=sp_tracks
b=a[a['popularity']>90].sort_values('popularity',ascending=False)[:10]
b[['name','popularity','artists']]

"""**4. Setting Release Date as the Index Column**"""

sp_tracks.set_index('release_date', inplace=True)
sp_tracks.index = pd.to_datetime(sp_tracks.index, errors='coerce', format='mixed')
years = sp_tracks.index.year
sp_tracks.head()

"""**5. Extracting Artist Name from the 18th Row of the Dataset**"""

sp_tracks[['artists']].iloc[18]

"""**6. Converting Song Duration from Milliseconds to Seconds**"""

sp_tracks['duration'] = sp_tracks['duration_ms'].apply (lambda x : round(x/1000))
sp_tracks.drop('duration_ms', inplace = True, axis=1)
sp_tracks.duration.head()

"""**7. Visualization: Pearson Correlation Heatmap for Two Variables**"""

td = sp_tracks.select_dtypes(include='number').corr(method='pearson')
plt.figure(figsize=(9,5))
hmap = sns.heatmap(td, annot = True, fmt = '.1g', vmin=-1, vmax=1, center=0, cmap='Greens', linewidths=0.1, linecolor='black')
hmap.set_title('Correlation HeatMap')
hmap.set_xticklabels(hmap.get_xticklabels(), rotation=90)

"""**8. Creating a 4% Sample of the Entire Dataset**"""

sample_sp=sp_tracks.sample(int(0.004*len(sp_tracks)))
print(len(sample_sp))

"""**9. Regression Plot of Loudness vs. Energy with Regression Line**"""

plt.figure(figsize=(8,4))
sns.regplot(data=sample_sp, y='loudness', x='energy', color='#054907').set(title='Regression Plot - Loudness vs Energy Correlation')

"""**10. Regression Plot of Popularity vs. Acousticness with Regression Line**"""

plt.figure(figsize=(8,4))
sns.regplot(data=sample_sp, y='popularity', x='acousticness', color='#008000').set(title='Regression Plot - Popularity vs Acousticness Correlation')

"""**11. Adding a New Column to the Tracks Table**"""

sp_tracks['dates']=sp_tracks.index.get_level_values('release_date')
sp_tracks.dates=pd.to_datetime(sp_tracks.dates)
years=sp_tracks.dates.dt.year
sp_tracks.head()

"""**12. Graph: Number of Songs per Year**"""

sns.displot(years, discrete=True, aspect=2, height=4, kind='hist',color='g').set(title='No of songs - per year')

"""**13. Line Graph: Duration of Songs Over Each Year**"""

total_dr = sp_tracks.duration
fig_dims = (15,5)
fig, ax = plt.subplots(figsize=fig_dims)
fig = sns.barplot(x = years, y = total_dr, ax = ax, err_kws={'linewidth': False}).set(title='Years vs Duration')
plt.xticks(rotation=90)